cardiointegro/analyse/urls.py
from django.urls import path

from . import views

app_name = 'analyse'

urlpatterns = [
    # Вывод списка анализов ЭКГ
    path('list/', views.analyse_list_view, name='list'),
    # Форма создания анализа ЭКГ
    path('create/', views.analyse_create_view, name='create'),
    # Вывод отчёта по анализу ЭКГ
    path('<int:pk>/', views.AnalyseDetailView.as_view(), name='detail'),
    # Поиск среди спика анализов ЭКГ
    path('search/', views.analyse_search_view, name='search'),
]

cardiointegro/cardiointegro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings

urlpatterns = [
    # Лендинги
    path('', include('landing.urls'), name='landing'),
    # Приложение для анализа ЭКГ
    path('analyse/', include('analyse.urls'), name='analyse'),
    # Приложение пользователя
    path('users/', include('users.urls')),
    # Приложение для управления профилем
    path('auth/', include('django.contrib.auth.urls'), name='users'),
    # Приложение админки
    path('ci_admin/', admin.site.urls),
    # Автоматическое обновление страниц для фронтенда
    # Автоматическое обновление страниц для фронтенда
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cardiointegro/landing/urls.py
from django.urls import path

from . import views

app_name = 'landing'

urlpatterns = [
    path('', views.feedback_view, name='main_page'),
    path('knowledgebase/', views.KnowledgebaseTemplateView.as_view(),
         name='knowledgebase'),
]

cardiointegro/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    # Регистрация
    path('registration/', views.CreateUserView.as_view(), name='registration'),
    # Аутентификация
    path('logout/', views.logout_view, name='logout'),
]

cardiointegro/templates/includes/analyse_table_element.html
<tr class="bg-white border-b hover:bg-gray-50 ">
  <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
    {{ analyse.title }}
  </th>
  <td class="px-6 py-4">
    {{ analyse.created_at }}
  </td>
  <td class="px-6 py-4">
    <span
      class="bg-green-100 text-green-800 font-medium me-2 px-2.5 py-0.5 rounded">Готово</span>
  </td>
  <td class="px-6 py-4 text-left">
    <a href="{% url 'analyse:detail' analyse.id %}" class="flex items-center p-2 text-blue-600 rounded-lg hover:bg-gray-100 hover:underline group">
      <svg class="w-6 h-6 text-blue-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
        fill="currentColor" viewBox="0 0 24 24">
        <path fill-rule="evenodd"
          d="M8 3a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1h2a2 2 0 0 1 2 2v15a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h2Zm6 1h-4v2H9a1 1 0 0 0 0 2h6a1 1 0 1 0 0-2h-1V4Z"
          clip-rule="evenodd" />
      </svg>
      <span>Просмотреть отчёт</span>
    </a>
  </td>
</tr>

cardiointegro/templates/includes/footer.html
<footer>
    <h1>Футер</h1>
</footer>

cardiointegro/templates/includes/knowledgebase.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block title %}База знаний{% endblock title %}

{% block content %}
<p>База знаний</p>
{% endblock %}

cardiointegro/templates/includes/sidebar.html
{% load static %}

<nav class="fixed top-0 z-50 w-full bg-gray-50">
  <div class="px-3 py-3 lg:px-5 lg:pl-3">
    <div class="flex flex-wrap items-center justify-between">
      <div class="flex items-center justify-start rtl:justify-end gap-1.5">
        <button data-drawer-target="logo-sidebar" data-drawer-toggle="logo-sidebar" aria-controls="logo-sidebar"
          type="button"
          class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200">
          <span class="sr-only">Открыть меню</span>
          <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg">
            <path clip-rule="evenodd" fill-rule="evenodd"
              d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z">
            </path>
          </svg>
        </button>
        <a href="{% url 'landing:main_page' %}" class="flex items-center mx-10 sm:mx-auto">
          <img src="{% static 'img/heart.ico' %}" alt="logo">
          <p class="text-3xl font-medium"><span class="text-red-600">Cardio</span><span
              class="text-gray-900">Integro</span></p>
        </a>
      </div>
      <div class="mx-auto">
        <p class="text-lg font-semibold text-gray-900">Личный кабинет врача</p>
      </div>
    </div>
  </div>
</nav>

<aside id="logo-sidebar"
  class="fixed top-0 left-0 z-40 w-64 bg-gray-50 h-screen pt-20 transition-transform -translate-x-full sm:translate-x-0 "
  aria-label="Sidebar">
  <div class="h-full px-3 pb-4 overflow-y-auto bg-gray-50">
    {% with request.resolver_match.view_name as view_name %}
    <ul class="space-y-2 font-medium mt-6 sm:mt-0">
      <li>
        <a href="{% url 'analyse:create' %}" class="flex items-center p-2 rounded-lg
          {% if view_name == 'analyse:create' %} text-white bg-blue-500 hover:opacity-90
          {% else %} text-gray-900 hover:bg-gray-100
          {% endif %} group">
          <svg class="flex-shrink-0 w-[26px] h-[26px]
          {% if view_name == 'analyse:create' %} text-white group-hover:text-white 
          {% else %} text-gray-500 group-hover:text-gray-900 
          {% endif %} transition duration-75" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24"
            height="24" fill="currentColor" viewBox="0 0 24 24">
            <path fill-rule="evenodd"
              d="M8 7V2.221a2 2 0 0 0-.5.365L3.586 6.5a2 2 0 0 0-.365.5H8Zm2 0V2h7a2 2 0 0 1 2 2v.126a5.087 5.087 0 0 0-4.74 1.368v.001l-6.642 6.642a3 3 0 0 0-.82 1.532l-.74 3.692a3 3 0 0 0 3.53 3.53l3.694-.738a3 3 0 0 0 1.532-.82L19 15.149V20a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9h5a2 2 0 0 0 2-2Z"
              clip-rule="evenodd" />
            <path fill-rule="evenodd"
              d="M17.447 8.08a1.087 1.087 0 0 1 1.187.238l.002.001a1.088 1.088 0 0 1 0 1.539l-.377.377-1.54-1.542.373-.374.002-.001c.1-.102.22-.182.353-.237Zm-2.143 2.027-4.644 4.644-.385 1.924 1.925-.385 4.644-4.642-1.54-1.54Zm2.56-4.11a3.087 3.087 0 0 0-2.187.909l-6.645 6.645a1 1 0 0 0-.274.51l-.739 3.693a1 1 0 0 0 1.177 1.176l3.693-.738a1 1 0 0 0 .51-.274l6.65-6.646a3.088 3.088 0 0 0-2.185-5.275Z"
              clip-rule="evenodd" />
          </svg>
          <span class="ms-3">Новый анализ</span>
        </a>
      </li>
      <li>
        <a href="{% url 'analyse:list' %}" class="flex items-center p-2 rounded-lg 
          {% if view_name == 'analyse:list' %} text-white bg-blue-500 hover:opacity-90
          {% else %} text-gray-900 hover:bg-gray-100
          {% endif %} group">
          <svg class="flex-shrink-0 w-6 h-6
          {% if view_name == 'analyse:list' %} text-white group-hover:text-white 
          {% else %} text-gray-500 group-hover:text-gray-900 
          {% endif %} transition duration-75" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor"
            viewBox="0 0 22 22">
            <path fill-rule="evenodd"
              d="M8 3a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1h2a2 2 0 0 1 2 2v15a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h2Zm6 1h-4v2H9a1 1 0 0 0 0 2h6a1 1 0 1 0 0-2h-1V4Zm-3 8a1 1 0 0 1 1-1h3a1 1 0 1 1 0 2h-3a1 1 0 0 1-1-1Zm-2-1a1 1 0 1 0 0 2h.01a1 1 0 1 0 0-2H9Zm2 5a1 1 0 0 1 1-1h3a1 1 0 1 1 0 2h-3a1 1 0 0 1-1-1Zm-2-1a1 1 0 1 0 0 2h.01a1 1 0 1 0 0-2H9Z"
              clip-rule="evenodd" />
          </svg>
          <span class="ms-3">Мои анализы</span>
        </a>
      </li>
      <li>
        <a href="{% url 'landing:knowledgebase' %}" class="flex items-center p-2 rounded-lg
          {% if view_name == 'landing:knowledgebase' %} text-white bg-blue-500 hover:opacity-90
          {% else %} text-gray-900 hover:bg-gray-100
          {% endif %} group">
          <svg class="flex-shrink-0 w-[26px] h-[26px]
          {% if view_name == 'landing:knowledgebase' %} text-white group-hover:text-white 
          {% else %} text-gray-500 group-hover:text-gray-900 
          {% endif %} transition duration-75" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24"
            height="24" fill="currentColor" viewBox="0 0 24 24">
            <path fill-rule="evenodd"
              d="M6 2a2 2 0 0 0-2 2v15a3 3 0 0 0 3 3h12a1 1 0 1 0 0-2h-2v-2h2a1 1 0 0 0 1-1V4a2 2 0 0 0-2-2h-8v16h5v2H7a1 1 0 1 1 0-2h1V2H6Z"
              clip-rule="evenodd" />
          </svg>

          <span class="flex-1 ms-3 whitespace-nowrap">База знаний</span>
        </a>
      </li>
      <li>
        <a href="{% url 'analyse:search' %}" class="flex items-center p-2 rounded-lg
          {% if view_name == 'analyse:search' %} text-white bg-blue-500 hover:opacity-90
          {% else %} text-gray-900 hover:bg-gray-100
          {% endif %} group">
          <svg class="flex-shrink-0 w-[26px] h-[26px]
          {% if view_name == 'analyse:search' %} text-white group-hover:text-white 
          {% else %} text-gray-500 group-hover:text-gray-900 
          {% endif %} transition duration-75" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24"
            height="24" fill="currentColor" viewBox="0 0 24 24">

            <path fill-rule="evenodd"
              d="M9 7V2.221a2 2 0 0 0-.5.365L4.586 6.5a2 2 0 0 0-.365.5H9Zm2 0V2h7a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V9h5a2 2 0 0 0 2-2Zm.5 5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3Zm0 5c.47 0 .917-.092 1.326-.26l1.967 1.967a1 1 0 0 0 1.414-1.414l-1.817-1.818A3.5 3.5 0 1 0 11.5 17Z"
              clip-rule="evenodd" />
          </svg>
          <span class="flex-1 ms-3 whitespace-nowrap">Поиск по пациентам</span>
        </a>
      </li>
    </ul>
    {% endwith %}
    <div id="dropdown-cta" class="p-4 mt-6 rounded-lg bg-blue-50 " role="alert">
      <div class="flex items-center mb-3">
        <span class="bg-orange-100 text-orange-800 text-sm font-semibold me-2 px-2.5 py-0.5 rounded">Beta</span>
        <button type="button"
          class="ms-auto -mx-1.5 -my-1.5 bg-blue-50 inline-flex justify-center items-center w-6 h-6 text-blue-900 rounded-lg focus:ring-2 focus:ring-blue-400 p-1 hover:bg-blue-200 h-6 w-6"
          data-dismiss-target="#dropdown-cta" aria-label="Close">
          <span class="sr-only">Закрыть</span>
          <svg class="w-2.5 h-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
            viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
          </svg>
        </button>
      </div>
      <p class="mb-3 text-sm text-blue-800">
        Информация на сайте является ознакомительной, не заменяя консультацию врача!<br><br>Оставаясь на сайте, вы
        соглашаетесь с
        <button data-modal-target="politic" data-modal-toggle="politic" class="text-sm text-blue-800 underline font-semibold hover:text-blue-900 text-start">Политикой конфиденциальности</button>
      </p>
    </div>
    <ul class="space-y-2 font-medium absolute bottom-3 px-3 py-4 overflow-y-auto bg-gray-50 w-60">
      {% if user.is_authenticated %}
      <li>
        <div class="flex items-center p-2 text-gray-900 rounded-lg group">
          <svg class="w-[26px] h-[26px] text-gray-800" aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
            <path fill-rule="evenodd"
              d="M12 4a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm-2 9a4 4 0 0 0-4 4v1a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2v-1a4 4 0 0 0-4-4h-4Z"
              clip-rule="evenodd" />
          </svg>
          <span class="flex-1 ms-3 whitespace-nowrap">{{ user.username }}</span>
        </div>
      </li>
      <li>
        <button type="button"
          class="flex items-center p-2 w-full text-base text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100"
          aria-controls="dropdown-authentication" data-collapse-toggle="dropdown-authentication">
          <svg class="w-[26px] h-[26px] text-gray-500 transition duration-75 group-hover:text-gray-900"
            aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
            viewBox="0 0 24 24">
            <path fill-rule="evenodd"
              d="M17 10v1.126c.367.095.714.24 1.032.428l.796-.797 1.415 1.415-.797.796c.188.318.333.665.428 1.032H21v2h-1.126c-.095.367-.24.714-.428 1.032l.797.796-1.415 1.415-.796-.797a3.979 3.979 0 0 1-1.032.428V20h-2v-1.126a3.977 3.977 0 0 1-1.032-.428l-.796.797-1.415-1.415.797-.796A3.975 3.975 0 0 1 12.126 16H11v-2h1.126c.095-.367.24-.714.428-1.032l-.797-.796 1.415-1.415.796.797A3.977 3.977 0 0 1 15 11.126V10h2Zm.406 3.578.016.016c.354.358.574.85.578 1.392v.028a2 2 0 0 1-3.409 1.406l-.01-.012a2 2 0 0 1 2.826-2.83ZM5 8a4 4 0 1 1 7.938.703 7.029 7.029 0 0 0-3.235 3.235A4 4 0 0 1 5 8Zm4.29 5H7a4 4 0 0 0-4 4v1a2 2 0 0 0 2 2h6.101A6.979 6.979 0 0 1 9 15c0-.695.101-1.366.29-2Z"
              clip-rule="evenodd" />
          </svg>
          <span class="flex-1 ml-3 text-left whitespace-nowrap">Настройки</span>
          <svg aria-hidden="true" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
              clip-rule="evenodd"></path>
          </svg>
        </button>
        <ul id="dropdown-authentication" class="hidden py-2 space-y-2">
          <li>
            <a href="{% url 'users:logout' %}"
              class="flex items-center p-2 pl-11 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100">Выйти</a>
          </li>
          <li>
            <a href="{% url 'password_change' %}"
              class="flex items-center p-2 pl-11 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100">Изменить
              пароль</a>
          </li>
          <li>
            <a href="{% url 'password_reset' %}"
              class="flex items-center p-2 pl-11 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100">Забыли
              пароль</a>
          </li>
        </ul>
      </li>
      {% else %}
      <li>
        <a href="{% url 'login' %}" class="flex items-center p-2 text-gray-900 rounded-lg group">
          <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 group-hover:text-gray-900"
            aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 16">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M1 8h11m0 0L8 4m4 4-4 4m4-11h3a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-3" />
          </svg>
          <span class="flex-1 ms-3 whitespace-nowrap">Войти</span>
        </a>
      </li>
      <li>
        <a href="{% url 'users:registration' %}" class="flex items-center p-2 text-gray-900 rounded-lg group">
          <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 group-hover:text-gray-900"
            aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M5 5V.13a2.96 2.96 0 0 0-1.293.749L.879 3.707A2.96 2.96 0 0 0 .13 5H5Z" />
            <path
              d="M6.737 11.061a2.961 2.961 0 0 1 .81-1.515l6.117-6.116A4.839 4.839 0 0 1 16 2.141V2a1.97 1.97 0 0 0-1.933-2H7v5a2 2 0 0 1-2 2H0v11a1.969 1.969 0 0 0 1.933 2h12.134A1.97 1.97 0 0 0 16 18v-3.093l-1.546 1.546c-.413.413-.94.695-1.513.81l-3.4.679a2.947 2.947 0 0 1-1.85-.227 2.96 2.96 0 0 1-1.635-3.257l.681-3.397Z" />
            <path
              d="M8.961 16a.93.93 0 0 0 .189-.019l3.4-.679a.961.961 0 0 0 .49-.263l6.118-6.117a2.884 2.884 0 0 0-4.079-4.078l-6.117 6.117a.96.96 0 0 0-.263.491l-.679 3.4A.961.961 0 0 0 8.961 16Zm7.477-9.8a.958.958 0 0 1 .68-.281.961.961 0 0 1 .682 1.644l-.315.315-1.36-1.36.313-.318Zm-5.911 5.911 4.236-4.236 1.359 1.359-4.236 4.237-1.7.339.341-1.699Z" />
          </svg>
          <span class="flex-1 ms-3 whitespace-nowrap">Зарегистрироваться</span>
        </a>
      </li>
      {% endif %}
    </ul>
  </div>
</aside>